let matchesData = [
  {
    matchNum: 1,
    group: 1,
    timestamp: "2026-06-11T19:00:00Z",
    teamOneAR: "",
    teamOne: "mexico",
    teamTwoAR: "جنوب أفريقيا",
    teamTwo: "south africa",
    teamOneFlag: "media/FLAGS/11/mx.svg",
    teamTwoFlag: "media/FLAGS/11/za.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 2,
    group: 1,
    timestamp: "2026-06-12T02:00:00Z",
    teamOneAR: "",
    teamOne: "south korea",
    teamTwoAR: "",
    teamTwo: "soon",
    teamOneFlag: "media/FLAGS/11/kr.svg",
    teamTwoFlag: "media/FLAGS/11/fifa.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 3,
    group: 2,
    timestamp: "2026-06-12T19:00:00Z",
    teamOneAR: "",
    teamOne: "canada",
    teamTwoAR: "",
    teamTwo: "soon",
    teamOneFlag: "media/FLAGS/11/ca.svg",
    teamTwoFlag: "media/FLAGS/11/fifa.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 5,
    group: 3,
    timestamp: "2026-06-13T23:00:00Z",
    teamOneAR: "",
    teamOne: "brazil",
    teamTwoAR: "",
    teamTwo: "morocco",
    teamOneFlag: "media/FLAGS/11/br.svg",
    teamTwoFlag: "media/FLAGS/11/ma.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 6,
    group: 3,
    timestamp: "2026-06-14T02:00:00Z",
    teamOneAR: "",
    teamOne: "haiti",
    teamTwoAR: "",
    teamTwo: "scotland",
    teamOneFlag: "media/FLAGS/11/ht.svg",
    teamTwoFlag: "media/FLAGS/11/gb-sct.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 7,
    group: 4,
    timestamp: "2026-06-13T01:00:00Z",
    teamOneAR: "",
    teamOne: "united stats",
    teamTwoAR: "",
    teamTwo: "paraguay",
    teamOneFlag: "media/FLAGS/11/us.svg",
    teamTwoFlag: "media/FLAGS/11/py.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 8,
    group: 2,
    timestamp: "2026-06-13T23:00:00Z",
    teamOneAR: "",
    teamOne: "qatar",
    teamTwoAR: "",
    teamTwo: "switzerland",
    teamOneFlag: "media/FLAGS/11/qa.svg",
    teamTwoFlag: "media/FLAGS/11/ch.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 8,
    group: 4,
    timestamp: "2026-06-13T21:00:00Z",
    teamOneAR: "",
    teamOne: "australia",
    teamTwoAR: "",
    teamTwo: "soon",
    teamOneFlag: "media/FLAGS/11/au.svg",
    teamTwoFlag: "media/FLAGS/11/fifa.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 9,
    group: 5,
    timestamp: "2026-06-14T23:00:00Z",
    teamOneAR: "",
    teamOne: "cote d ivoire",
    teamTwoAR: "",
    teamTwo: "ecuador",
    teamOneFlag: "media/FLAGS/11/ci.svg",
    teamTwoFlag: "media/FLAGS/11/ec.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 10,
    group: 5,
    timestamp: "2026-06-14T17:00:00Z",
    teamOneAR: "",
    teamOne: "germany",
    teamTwoAR: "",
    teamTwo: "curacao",
    teamOneFlag: "media/FLAGS/11/de.svg",
    teamTwoFlag: "media/FLAGS/11/cw.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 11,
    group: 6,
    timestamp: "2026-06-14T20:00:00Z",
    teamOneAR: "",
    teamOne: "netherlands",
    teamTwoAR: "",
    teamTwo: "japan",
    teamOneFlag: "media/FLAGS/11/nl.svg",
    teamTwoFlag: "media/FLAGS/11/jp.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 12,
    group: 6,
    timestamp: "2026-06-15T02:00:00Z",
    teamOneAR: "",
    teamOne: "tunisia",
    teamTwoAR: "",
    teamTwo: "soon",
    teamOneFlag: "media/FLAGS/11/tn.svg",
    teamTwoFlag: "media/FLAGS/11/fifa.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 13,
    group: 8,
    timestamp: "2026-06-16T01:00:00Z",
    teamOneAR: "",
    teamOne: "spain",
    teamTwoAR: "",
    teamTwo: "cabo verde",
    teamOneFlag: "media/FLAGS/11/es.svg",
    teamTwoFlag: "media/FLAGS/11/cv.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 14,
    group: 8,
    timestamp: "2026-06-16T07:00:00Z",
    teamOneAR: "",
    teamOne: "saudi arabia",
    teamTwoAR: "",
    teamTwo: "uruguay",
    teamOneFlag: "media/FLAGS/11/sa.svg",
    teamTwoFlag: "media/FLAGS/11/uy.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 16,
    group: 2,
    timestamp: "2026-06-18T22:00:00Z",
    teamOneAR: "",
    teamOne: "switzerland",
    teamTwoAR: "",
    teamTwo: "soon",
    teamOneFlag: "media/FLAGS/11/ch.svg",
    teamTwoFlag: "media/FLAGS/11/fifa.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 17,
    group: 9,
    timestamp: "2026-06-16T19:00:00Z",
    teamOneAR: "",
    teamOne: "france",
    teamTwoAR: "",
    teamTwo: "senegal",
    teamOneFlag: "media/FLAGS/11/fr.svg",
    teamTwoFlag: "media/FLAGS/11/sn.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 18,
    group: 9,
    timestamp: "2026-06-17T22:00:00Z",
    teamOneAR: "",
    teamOne: "norway",
    teamTwoAR: "",
    teamTwo: "soon",
    teamOneFlag: "media/FLAGS/11/no.svg",
    teamTwoFlag: "media/FLAGS/11/fifa.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 19,
    group: 7,
    timestamp: "2026-06-15T19:00:00Z",
    teamOneAR: "",
    teamOne: "belgium",
    teamTwoAR: "",
    teamTwo: "egypt",
    teamOneFlag: "media/FLAGS/11/be.svg",
    teamTwoFlag: "media/FLAGS/11/eg.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 19,
    group: 10,
    timestamp: "2026-06-17T01:00:00Z",
    teamOneAR: "",
    teamOne: "argentina",
    teamTwoAR: "",
    teamTwo: "algeria",
    teamOneFlag: "media/FLAGS/11/ar.svg",
    teamTwoFlag: "media/FLAGS/11/dz.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 20,
    group: 7,
    timestamp: "2026-06-16T01:00:00Z",
    teamOneAR: "",
    teamOne: "ir iran",
    teamTwoAR: "",
    teamTwo: "new zealand",
    teamOneFlag: "media/FLAGS/11/ir.svg",
    teamTwoFlag: "media/FLAGS/11/nz.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 20,
    group: 10,
    timestamp: "2026-06-17T04:00:00Z",
    teamOneAR: "",
    teamOne: "austria",
    teamTwoAR: "",
    teamTwo: "jordan",
    teamOneFlag: "media/FLAGS/11/at.svg",
    teamTwoFlag: "media/FLAGS/11/jo.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 21,
    group: 11,
    timestamp: "2026-06-17T17:00:00Z",
    teamOneAR: "",
    teamOne: "portugal",
    teamTwoAR: "",
    teamTwo: "soon",
    teamOneFlag: "media/FLAGS/11/pt.svg",
    teamTwoFlag: "media/FLAGS/11/fifa.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 22,
    group: 11,
    timestamp: "2026-06-18T02:00:00Z",
    teamOneAR: "",
    teamOne: "uzbekistan",
    teamTwoAR: "",
    teamTwo: "colombia",
    teamOneFlag: "media/FLAGS/11/uz.svg",
    teamTwoFlag: "media/FLAGS/11/co.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 23,
    group: 12,
    timestamp: "2026-06-17T21:00:00Z",
    teamOneAR: "",
    teamOne: "england",
    teamTwoAR: "",
    teamTwo: "croatia",
    teamOneFlag: "media/FLAGS/11/gb-eng.svg",
    teamTwoFlag: "media/FLAGS/11/hr.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 24,
    group: 12,
    timestamp: "2026-06-18T02:00:00Z",
    teamOneAR: "",
    teamOne: "ghana",
    teamTwoAR: "",
    teamTwo: "panama",
    teamOneFlag: "media/FLAGS/11/gh.svg",
    teamTwoFlag: "media/FLAGS/11/pa.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 25,
    group: 1,
    timestamp: "2026-06-18T19:00:00Z",
    teamOneAR: "جنوب أفريقيا",
    teamOne: "south africa",
    teamTwoAR: "",
    teamTwo: "soon",
    teamOneFlag: "media/FLAGS/11/za.svg",
    teamTwoFlag: "media/FLAGS/11/fifa.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 27,
    group: 2,
    timestamp: "2026-06-19T01:00:00Z",
    teamOneAR: "",
    teamOne: "canada",
    teamTwoAR: "",
    teamTwo: "qatar",
    teamOneFlag: "media/FLAGS/11/ca.svg",
    teamTwoFlag: "media/FLAGS/11/qa.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 28,
    group: 1,
    timestamp: "2026-06-19T04:00:00Z",
    teamOneAR: "",
    teamOne: "mexico",
    teamTwoAR: "",
    teamTwo: "south korea",
    teamOneFlag: "media/FLAGS/11/mx.svg",
    teamTwoFlag: "media/FLAGS/11/kr.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 29,
    group: 3,
    timestamp: "2026-06-19T21:00:00Z",
    teamOneAR: "",
    teamOne: "brazil",
    teamTwoAR: "",
    teamTwo: "haiti",
    teamOneFlag: "media/FLAGS/11/br.svg",
    teamTwoFlag: "media/FLAGS/11/ht.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 30,
    group: 3,
    timestamp: "2026-06-20T00:00:00Z",
    teamOneAR: "",
    teamOne: "morocco",
    teamTwoAR: "",
    teamTwo: "scotland",
    teamOneFlag: "media/FLAGS/11/ma.svg",
    teamTwoFlag: "media/FLAGS/11/gb-sct.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 31,
    group: 4,
    timestamp: "2026-06-19T22:00:00Z",
    teamOneAR: "",
    teamOne: "paraguay",
    teamTwoAR: "",
    teamTwo: "soon",
    teamOneFlag: "media/FLAGS/11/py.svg",
    teamTwoFlag: "media/FLAGS/11/fifa.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 32,
    group: 4,
    timestamp: "2026-06-20T01:00:00Z",
    teamOneAR: "",
    teamOne: "united stats",
    teamTwoAR: "",
    teamTwo: "australia",
    teamOneFlag: "media/FLAGS/11/us.svg",
    teamTwoFlag: "media/FLAGS/11/au.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 33,
    group: 5,
    timestamp: "2026-06-20T20:00:00Z",
    teamOneAR: "",
    teamOne: "germany",
    teamTwoAR: "",
    teamTwo: "cote d ivoire",
    teamOneFlag: "media/FLAGS/11/de.svg",
    teamTwoFlag: "media/FLAGS/11/ci.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 34,
    group: 5,
    timestamp: "2026-06-21T00:00:00Z",
    teamOneAR: "",
    teamOne: "curacao",
    teamTwoAR: "",
    teamTwo: "ecuador",
    teamOneFlag: "media/FLAGS/11/cw.svg",
    teamTwoFlag: "media/FLAGS/11/ec.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 35,
    group: 6,
    timestamp: "2026-06-20T20:00:00Z",
    teamOneAR: "",
    teamOne: "japan",
    teamTwoAR: "",
    teamTwo: "soon",
    teamOneFlag: "media/FLAGS/11/jp.svg",
    teamTwoFlag: "media/FLAGS/11/fifa.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 36,
    group: 6,
    timestamp: "2026-06-21T04:00:00Z",
    teamOneAR: "",
    teamOne: "netherlands",
    teamTwoAR: "",
    teamTwo: "tunisia",
    teamOneFlag: "media/FLAGS/11/nl.svg",
    teamTwoFlag: "media/FLAGS/11/tn.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 41,
    group: 9,
    timestamp: "2026-06-22T21:00:00Z",
    teamOneAR: "",
    teamOne: "france",
    teamTwoAR: "",
    teamTwo: "soon",
    teamOneFlag: "media/FLAGS/11/fr.svg",
    teamTwoFlag: "media/FLAGS/11/fifa.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 42,
    group: 9,
    timestamp: "2026-06-23T00:00:00Z",
    teamOneAR: "",
    teamOne: "senegal",
    teamTwoAR: "",
    teamTwo: "norway",
    teamOneFlag: "media/FLAGS/11/sn.svg",
    teamTwoFlag: "media/FLAGS/11/no.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 43,
    group: 7,
    timestamp: "2026-06-19T21:00:00Z",
    teamOneAR: "",
    teamOne: "belgium",
    teamTwoAR: "",
    teamTwo: "ir iran",
    teamOneFlag: "media/FLAGS/11/be.svg",
    teamTwoFlag: "media/FLAGS/11/ir.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 43,
    group: 10,
    timestamp: "2026-06-17T22:00:00Z",
    teamOneAR: "",
    teamOne: "argentina",
    teamTwoAR: "",
    teamTwo: "austria",
    teamOneFlag: "media/FLAGS/11/ar.svg",
    teamTwoFlag: "media/FLAGS/11/at.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 44,
    group: 7,
    timestamp: "2026-06-22T01:00:00Z",
    teamOneAR: "",
    teamOne: "egypt",
    teamTwoAR: "",
    teamTwo: "new zealand",
    teamOneFlag: "media/FLAGS/11/eg.svg",
    teamTwoFlag: "media/FLAGS/11/nz.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 44,
    group: 10,
    timestamp: "2026-06-23T03:00:00Z",
    teamOneAR: "",
    teamOne: "algeria",
    teamTwoAR: "",
    teamTwo: "jordan",
    teamOneFlag: "media/FLAGS/11/dz.svg",
    teamTwoFlag: "media/FLAGS/11/jo.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 45,
    group: 8,
    timestamp: "2026-06-21T17:00:00Z",
    teamOneAR: "",
    teamOne: "spain",
    teamTwoAR: "",
    teamTwo: "saudi arabia",
    teamOneFlag: "media/FLAGS/11/es.svg",
    teamTwoFlag: "media/FLAGS/11/sa.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 45,
    group: 11,
    timestamp: "2026-06-23T17:00:00Z",
    teamOneAR: "",
    teamOne: "portugal",
    teamTwoAR: "",
    teamTwo: "uzbekistan",
    teamOneFlag: "media/FLAGS/11/pt.svg",
    teamTwoFlag: "media/FLAGS/11/uz.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 46,
    group: 8,
    timestamp: "2026-06-22T01:00:00Z",
    teamOneAR: "",
    teamOne: "cabo verde",
    teamTwoAR: "",
    teamTwo: "uruguay",
    teamOneFlag: "media/FLAGS/11/cv.svg",
    teamTwoFlag: "media/FLAGS/11/uy.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 46,
    group: 11,
    timestamp: "2026-06-23T23:00:00Z",
    teamOneAR: "",
    teamOne: "colombia",
    teamTwoAR: "",
    teamTwo: "soon",
    teamOneFlag: "media/FLAGS/11/co.svg",
    teamTwoFlag: "media/FLAGS/11/fifa.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 47,
    group: 12,
    timestamp: "2026-06-23T21:00:00Z",
    teamOneAR: "",
    teamOne: "england",
    teamTwoAR: "",
    teamTwo: "ghana",
    teamOneFlag: "media/FLAGS/11/gb-eng.svg",
    teamTwoFlag: "media/FLAGS/11/gh.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 48,
    group: 12,
    timestamp: "2026-06-24T00:00:00Z",
    teamOneAR: "",
    teamOne: "croatia",
    teamTwoAR: "",
    teamTwo: "panama",
    teamOneFlag: "media/FLAGS/11/hr.svg",
    teamTwoFlag: "media/FLAGS/11/pa.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 49,
    group: 3,
    timestamp: "2026-06-24T18:00:00Z",
    teamOneAR: "",
    teamOne: "brazil",
    teamTwoAR: "",
    teamTwo: "scotland",
    teamOneFlag: "media/FLAGS/11/br.svg",
    teamTwoFlag: "media/FLAGS/11/gb-sct.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 50,
    group: 3,
    timestamp: "2026-06-24T18:00:00Z",
    teamOneAR: "",
    teamOne: "morocco",
    teamTwoAR: "",
    teamTwo: "haiti",
    teamOneFlag: "media/FLAGS/11/ma.svg",
    teamTwoFlag: "media/FLAGS/11/ht.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 51,
    group: 2,
    timestamp: "2026-06-24T20:00:00Z",
    teamOneAR: "",
    teamOne: "canada",
    teamTwoAR: "",
    teamTwo: "switzerland",
    teamOneFlag: "media/FLAGS/11/ca.svg",
    teamTwoFlag: "media/FLAGS/11/ch.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 52,
    group: 2,
    timestamp: "2026-06-24T20:00:00Z",
    teamOneAR: "",
    teamOne: "qatar",
    teamTwoAR: "",
    teamTwo: "soon",
    teamOneFlag: "media/FLAGS/11/qa.svg",
    teamTwoFlag: "media/FLAGS/11/fifa.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 53,
    group: 1,
    timestamp: "2026-06-24T23:00:00Z",
    teamOneAR: "",
    teamOne: "mexico",
    teamTwoAR: "",
    teamTwo: "soon",
    teamOneFlag: "media/FLAGS/11/mx.svg",
    teamTwoFlag: "media/FLAGS/11/fifa.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 54,
    group: 1,
    timestamp: "2026-06-24T23:00:00Z",
    teamOneAR: "جنوب أفريقيا",
    teamOne: "south africa",
    teamTwoAR: "",
    teamTwo: "south korea",
    teamOneFlag: "media/FLAGS/11/za.svg",
    teamTwoFlag: "media/FLAGS/11/kr.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 57,
    group: 5,
    timestamp: "2026-06-25T20:00:00Z",
    teamOneAR: "",
    teamOne: "germany",
    teamTwoAR: "",
    teamTwo: "ecuador",
    teamOneFlag: "media/FLAGS/11/de.svg",
    teamTwoFlag: "media/FLAGS/11/ec.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 58,
    group: 5,
    timestamp: "2026-06-25T20:00:00Z",
    teamOneAR: "",
    teamOne: "curacao",
    teamTwoAR: "",
    teamTwo: "cote d ivoire",
    teamOneFlag: "media/FLAGS/11/cw.svg",
    teamTwoFlag: "media/FLAGS/11/ci.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 59,
    group: 4,
    timestamp: "2026-06-26T01:00:00Z",
    teamOneAR: "",
    teamOne: "united stats",
    teamTwoAR: "",
    teamTwo: "soon",
    teamOneFlag: "media/FLAGS/11/us.svg",
    teamTwoFlag: "media/FLAGS/11/fifa.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 59,
    group: 6,
    timestamp: "2026-06-25T23:00:00Z",
    teamOneAR: "",
    teamOne: "japan",
    teamTwoAR: "",
    teamTwo: "tunisia",
    teamOneFlag: "media/FLAGS/11/jp.svg",
    teamTwoFlag: "media/FLAGS/11/tn.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 60,
    group: 4,
    timestamp: "2026-06-26T01:00:00Z",
    teamOneAR: "",
    teamOne: "paraguay",
    teamTwoAR: "",
    teamTwo: "australia",
    teamOneFlag: "media/FLAGS/11/py.svg",
    teamTwoFlag: "media/FLAGS/11/au.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 60,
    group: 6,
    timestamp: "2026-06-25T23:00:00Z",
    teamOneAR: "",
    teamOne: "netherlands",
    teamTwoAR: "",
    teamTwo: "soon",
    teamOneFlag: "media/FLAGS/11/nl.svg",
    teamTwoFlag: "media/FLAGS/11/fifa.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 65,
    group: 9,
    timestamp: "2026-06-26T19:00:00Z",
    teamOneAR: "",
    teamOne: "france",
    teamTwoAR: "",
    teamTwo: "norway",
    teamOneFlag: "media/FLAGS/11/fr.svg",
    teamTwoFlag: "media/FLAGS/11/no.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 66,
    group: 9,
    timestamp: "2026-06-26T19:00:00Z",
    teamOneAR: "",
    teamOne: "senegal",
    teamTwoAR: "",
    teamTwo: "soon",
    teamOneFlag: "media/FLAGS/11/sn.svg",
    teamTwoFlag: "media/FLAGS/11/fifa.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 67,
    group: 7,
    timestamp: "2026-06-27T03:00:00Z",
    teamOneAR: "",
    teamOne: "egypt",
    teamTwoAR: "",
    teamTwo: "ir iran",
    teamOneFlag: "media/FLAGS/11/eg.svg",
    teamTwoFlag: "media/FLAGS/11/ir.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 67,
    group: 10,
    timestamp: "2026-06-28T02:00:00Z",
    teamOneAR: "",
    teamOne: "argentina",
    teamTwoAR: "",
    teamTwo: "jordan",
    teamOneFlag: "media/FLAGS/11/ar.svg",
    teamTwoFlag: "media/FLAGS/11/jo.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 68,
    group: 7,
    timestamp: "2026-06-27T03:00:00Z",
    teamOneAR: "",
    teamOne: "belgium",
    teamTwoAR: "",
    teamTwo: "new zealand",
    teamOneFlag: "media/FLAGS/11/be.svg",
    teamTwoFlag: "media/FLAGS/11/nz.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 68,
    group: 10,
    timestamp: "2026-06-28T02:00:00Z",
    teamOneAR: "",
    teamOne: "algeria",
    teamTwoAR: "",
    teamTwo: "austria",
    teamOneFlag: "media/FLAGS/11/dz.svg",
    teamTwoFlag: "media/FLAGS/11/at.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 69,
    group: 8,
    timestamp: "2026-06-27T00:00:00Z",
    teamOneAR: "",
    teamOne: "cabo verde",
    teamTwoAR: "",
    teamTwo: "saudi arabia",
    teamOneFlag: "media/FLAGS/11/cv.svg",
    teamTwoFlag: "media/FLAGS/11/sa.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 69,
    group: 11,
    timestamp: "2026-06-27T23:30:00Z",
    teamOneAR: "",
    teamOne: "portugal",
    teamTwoAR: "",
    teamTwo: "colombia",
    teamOneFlag: "media/FLAGS/11/pt.svg",
    teamTwoFlag: "media/FLAGS/11/co.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 70,
    group: 8,
    timestamp: "2026-06-27T00:00:00Z",
    teamOneAR: "",
    teamOne: "spain",
    teamTwoAR: "",
    teamTwo: "uruguay",
    teamOneFlag: "media/FLAGS/11/es.svg",
    teamTwoFlag: "media/FLAGS/11/uy.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 70,
    group: 11,
    timestamp: "2026-06-27T23:30:00Z",
    teamOneAR: "",
    teamOne: "uzbekistan",
    teamTwoAR: "",
    teamTwo: "soon",
    teamOneFlag: "media/FLAGS/11/uz.svg",
    teamTwoFlag: "media/FLAGS/11/fifa.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
  {
    matchNum: 71,
    group: 12,
    timestamp: "2026-06-27T22:00:00Z",
    teamOneAR: "",
    teamOne: "england",
    teamTwoAR: "",
    teamTwo: "panama",
    teamOneFlag: "media/FLAGS/11/gb-eng.svg",
    teamTwoFlag: "media/FLAGS/11/pa.svg",
    teamOneScore: "6",
    teamTwoScore: "1",
    place: ["", ""],
  },
  {
    matchNum: 72,
    group: 12,
    timestamp: "2026-06-27T22:00:00Z",
    teamOneAR: "",
    teamOne: "croatia",
    teamTwoAR: "",
    teamTwo: "ghana",
    teamOneFlag: "media/FLAGS/11/hr.svg",
    teamTwoFlag: "media/FLAGS/11/gh.svg",
    teamOneScore: "-",
    teamTwoScore: "-",
    place: ["", ""],
  },
];
